### ISSUE TITLE
[Question] Framework integration/Shopware integration

### ISSUE THREAD

**Issue by pwnyprod** [PSC7-Helper/psc7-helper#3]
Hey,

was haltet Ihr davon das ganze in ein Framework wie Symfony oder Laravel zu packen. Würde den Vorteil bringen das Funktionen wie Login, Configs, PSR-4 Loading etc schon vorgebaut sind mit Validierung etc.

Auf der anderen Seite, da das Projekt ja quasi eine PSC7 Erweiterung ist wäre es vll besser das ganze als ein Shopware Plugin zu porten. Würde die gleichen Vorteile bieten und bietet dazu auch noch eine für den Endkunden easy-to-use Installationsmöglichkeit. Dazu stellt sich nur die Frage das ganze auf einen Routing Controller auslagern der den Login und die Routen macht oder ins ExtJS im SW Backend einfügen was (wie ich finde) ugly ist. Alternativ dazu könnte man auf SW 6.0 warten damit, da dann ExtJS weg kommt.

Habt ihr Ideen dazu @fwehrhausen @michael-rusch @alea123 ?

**Comment by fwehrhausen** [comment]
Hallo,

Wir sind gerade dran, das Ganze umzustrukturieren, mit MVC.

Über die Plugin Lösung haben wir auch schon nachgedacht, was natürlich ich hier als Nachteil empfinde, sind die 100€ pro Monat...

Mit freundlichen Grüßen 

Florian Wehrhausen

**Comment by pwnyprod** [comment]
Symfony und Laravel arbeiten beide nach dem Pattern ;)

100€ pro Monat?

**Comment by fwehrhausen** [comment]
Ja diese Shopware Dev-Lizens oder so, womit man dann sein Shopware-Plugin in den Store stellen kann. Nur so wäre es auch für den End-Nutzer wirklich eine Easy-Install-Möglichkeit ;-)

**Comment by pwnyprod** [comment]
Naja, braucht man ja nicht zwangsmäßig, kannst ja auch hier in den Tags einfach die kompilierte zip für den upload install im backend per sw-tools packen und dann geht das auch. Dann kann der Endkunde die auch easy einfach runterladen und im backend installieren. Halt alles ohne Lizensierung ¯\_(ツ)_/¯

**Comment by pwnyprod** [comment]
Hab grade auch kurz mal mit meinem CEO geredet, wenn die Dev-Lizenz nur die Hürde ist, könnten wir das auch über unsere Dev-Lizenz in den Store laden.

**Comment by fwehrhausen** [comment]
Ja gut, erst einmal müsste natürlich das Plugin noch entwickelt werden ;-) Denke aber gerne vorraus und wollte die Thermatik nur einmal ansprechen, dass ist aber ein nettes Angebot ;-)

**Comment by pwnyprod** [comment]
Klar, Pluginentwicklung wäre ich auch voll dabei :smirk:  Ist ja auch ein geiles Tool was ihr ins Leben gerufen habt :open_hands:

**Comment by pwnyprod** [comment]
In der Zeit halte ich schon mal fest was mir als enhancements einfällt :smiley: Kannst das gerne auch alles Taggen etc, ich kann das ja außerhalb der Organisation nicht.

**Comment by michael-rusch** [comment]
Hi. Ich habe ein Mini-Framework gebastelt und baue gerade alle gesammelten Funktion für die neue Version des Helpers um. Es dauert leider noch Wochen bis ich alles soweit habe. Danach muss das Design noch schön gemacht werden.

**Comment by pwnyprod** [comment]
Kann man sich das irgendwo anschauen?

**Comment by michael-rusch** [comment]
Das liegt bei Bitbucket. Wenn die anderen beiden Protagonisten das auch wollen, kannst di das da gern ansehen. @fwehrhausen  @alea123

**Comment by fwehrhausen** [comment]
Von mir aus: Grünes Licht ;-)

**Comment by alea123** [comment]
+

**Comment by michael-rusch** [comment]
@pwnyprod sende mit mal deinen Benutzernamen oder E-Mail-Adresse bei Bitbucket.

**Comment by pwnyprod** [comment]
jhoppe1

**Comment by michael-rusch** [comment]
done
