### ISSUE TITLE
[enhancement] Integration of Unit Tests

### ISSUE THREAD

**Issue by pwnyprod** [PSC7-Helper/psc7-helper#4]
Integration of Php Unit Tests for CI Integration and Building.
(Wichtig für Open Source Entwicklung mit vielen Contributors)

https://phpunit.de/

**Comment by michael-rusch** [comment]
Puhhh. Gleich in die Vollen. Bei diesem Projekt können wir darüber sprechen, wenn wir ein gutes Grundgerüst haben, an dem auch andere Entwickeln wollen.

**Comment by pwnyprod** [comment]
Das sind momentan alles nur sachen die mir eingefallen sind die man noch integrieren könnte. Hatte mit @fwehrhausen schon darüber geredet. Das hier ist eher ein spätes Feature auf der Roadmap, und sowieso erst zu integrieren wenn eine Framework entscheidung getroffen wurde.
